image: erratik/ci-k8s

stages:
  # - setup
  - build
  - gcloud
  - deploy

include:
  # - local: "/.ci/cache.yml"
  # - local: "/.ci/setup.yml"
  - local: "/.ci/build-image.yml"
  - local: "/.ci/gcloud-auth.yml"

#

build:
  stage: build
  script: echo "toto"
