version: "3.1"
services:
  zelda_api:
    image: node:9.6.1-alpine
    container_name: local_oni
    working_dir: /app
    environment:
      - MINIO_HOST=minio
      - REDIS_HOST=redis
    ports:
      - "4529:4529"
    volumes:
      - $PWD/tmp:/app/tmp
      - $PWD/dist:/app/dist
      - $PWD/node_modules:/app/node_modules
      - $PWD/package.json:/app/package.json
    command: ["npm", "run", "serve"]

  minio:
    image: minio/minio
    volumes:
      - minio:/data
      - minio-config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=dna_admin
      - MINIO_SECRET_KEY=password
    ports:
      - "9000:9000" # you can override it via docker-compose.override.yml
    command: server /data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  minio:
  minio-config:
