version: '3.7'

volumes:
  mongo:
  redis:

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

services:
  oni_redis:
    container_name: oni_redis
    image: redis
    networks:
      - mongo_net
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

  # MongoDB and document data store
  init:
    container_name: init
    image: erratik/kusanagi-init
    environment:
      - USEIP=172.16.0.3
    restart: always
    networks:
      mongo_net:
        ipv4_address: 172.16.0.3
    ports:
      - '27017:27017'
    command: ./run.sh

  mongo:
    container_name: mongo
    image: mongo
    depends_on:
      - init
    networks:
      mongo_net:
    volumes:
      - mongo:/data
      - ./data/datawhore:/data/datawhore
    command: mongorestore --host=172.16.0.3 --db datawhore -u erratik -p kaya80ate ./data/datawhore
    # logging:
    #   driver: none

  oni:
    image: node:9.6.1-alpine
    container_name: local_oni
    working_dir: /app
    depends_on:
      - oni_redis
      - mongo
    networks:
      mongo_net:
    environment:
      - REDIS_HOST=oni_redis
      - CORS_ORIGIN=http://localhost:10011, http://datawhore.erratik.ca:10011
      - NODE_ENV=dev
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URI=mongodb://erratik:kaya80ate@172.16.0.3:27017/datawhore
      - SESSION_SECRET=fiddle-farter
      - PORT=10011
    ports:
      - '10011:10011'
      - '127.0.0.1:9229:9229'
    volumes:
      - $PWD/tmp:/app/tmp
      - $PWD/dist:/app/dist
      - $PWD/node_modules:/app/node_modules
      - $PWD/package.json:/app/package.json
    command: node --inspect=0.0.0.0:9229 /app/dist/main.js
    restart: always
