{{- $name := include "oni.name" . -}}
{{- $fullName := include "oni.fullname" . -}}
{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ .Values.global.app }}
    component: {{ $name }}
    chart: {{ template "oni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 6379
  selector:
    app: {{ .Values.global.app }}
    component: {{ $name }}
    release: {{ .Release.Name }}
{{- end }}
